---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    extra_args: "{{ pip_extra_args }}"
  with_items: "{{ pip_install_packages }}"

